# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-11-15 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='验证码'),
            preserve_default=False,
        ),
    ]
