# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-11-15 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201115_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='code',
            field=models.CharField(max_length=100, verbose_name='验证码'),
        ),
    ]
