# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-11-15 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201115_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='code',
            field=models.TextField(verbose_name='验证码'),
        ),
    ]
