# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-11-15 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0003_auto_20160715_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='key',
            field=models.TextField(max_length=256, verbose_name='Settings Key'),
        ),
    ]
